spring.application.name=user-service

server.servlet.context-path=/users
server.port = 9020

spring.datasource.url=jdbc:postgresql://localhost:5432/user_DB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=${JWT_SECRET}
eureka.client.service-url.defaultZone= http://localhost:8761/eureka